// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtIbBII4a3M3uRsDc0CTgsmauA3ijL7Q',
    appId: '1:388318824077:web:df5fdf8920fedaa66f04c4',
    messagingSenderId: '388318824077',
    projectId: 'firestoredata-90c6c',
    authDomain: 'firestoredata-90c6c.firebaseapp.com',
    storageBucket: 'firestoredata-90c6c.appspot.com',
    measurementId: 'G-KTLE4E53HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9ZK2un3yuOcHfjo5Gt3_KS4jV6N-PqA',
    appId: '1:388318824077:android:6ab373bdfbc18d8c6f04c4',
    messagingSenderId: '388318824077',
    projectId: 'firestoredata-90c6c',
    storageBucket: 'firestoredata-90c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9UCvEzN_Bz8bCsNJhd1Yt7aPcTIgYO9I',
    appId: '1:388318824077:ios:585113326cd2dbd56f04c4',
    messagingSenderId: '388318824077',
    projectId: 'firestoredata-90c6c',
    storageBucket: 'firestoredata-90c6c.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9UCvEzN_Bz8bCsNJhd1Yt7aPcTIgYO9I',
    appId: '1:388318824077:ios:f5d2f63329bbe2156f04c4',
    messagingSenderId: '388318824077',
    projectId: 'firestoredata-90c6c',
    storageBucket: 'firestoredata-90c6c.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
